DROP TABLE IF EXISTS users cascade;
DROP TABLE IF EXISTS memes cascade;
DROP TABLE IF EXISTS meme_tags cascade;

CREATE TABLE users (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email VARCHAR UNIQUE,
  password_hash VARCHAR NOT NULL,
  user_name VARCHAR NOT NULL
);

CREATE TABLE memes (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  url VARCHAR
);

CREATE TABLE meme_tags (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  meme_id INT NOT NULL,
  FOREIGN KEY (meme_id) REFERENCES memes(id),
  tag VARCHAR,
  confidence DECIMAL
);

CREATE TABLE user_image (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  url VARCHAR
  user_id INT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE user_tags (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_image_id INT NOT NULL,
  FOREIGN KEY (user_image_id) REFERENCES user_image(id),
  tag VARCHAR,
  confidence DECIMAL
);
